version: "3.8"

services:
  telegram-bot:
    build: .
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./docs:/app/docs
      - ./chroma_db:/app/chroma_db
    depends_on:
      - ingest

  ingest:
    build: .
    env_file: .env
    volumes:
      - ./docs:/app/docs
      - ./chroma_db:/app/chroma_db
    command: python ingest_docs.py
    restart: "no"
