# To create the conda environment, run:
#   conda env create -f environment.yml
name: telegram-bot
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.13.3
  - python-telegram-bot=22.0
  - python-dotenv=1.1.0
  - openai=1.77
  - chromadb=1.0.9
